import {Platform, StyleSheet} from 'react-native';
import {SCREEN_WIDTH} from '@stargazers/utils/dimensions';
import {Fonts} from '@stargazers/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 0,
    width: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  panel: {
    width: '85%',
    maxWidth: 400,
    padding: 20,
    paddingTop: 15,
    height: 310,
    borderWidth: 1,
    borderRadius: 20,
    borderColor: '#35485b',
    borderBottomWidth: 0,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 1,
    position: 'absolute',
    transform: [{translateY: 180}],
    zIndex: 2000,
    ...Platform.select({
      ios: {},
      android: {
        marginTop: -10,
        shadowOffset: {width: 0, height: 2},
        elevation: 15,
      },
    }),
  },
  panelSync: {
    width: 150,
    height: 150,
    padding: 20,
    paddingTop: 15,
    borderWidth: 1,
    borderRadius: 20,
    borderColor: '#FFF',
    borderBottomWidth: 0,
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 6,
    elevation: 3,
    position: 'absolute',
    transform: [{translateY: 800}],
    zIndex: 1200,
    ...Platform.select({
      ios: {},
      android: {
        marginTop: -10,
        shadowOffset: {width: 0, height: 5},
        elevation: 7,
      },
    }),
  },
  logoContainer: {
    flex: 1,
    position: 'absolute',
    top: 69,
  },
  image: {
    width: 100,
    height: 80,
    marginBottom: 10,
    marginLeft: 53,
    overflow: 'visible',
  },
  overlay: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(255,255,255,0.12)',
    zIndex: 1000,
  },
  footer: {
    paddingHorizontal: 22,
    bottom: 0,
    fontSize: 12,
    lineHeight: 20,
    position: 'absolute',
    maxWidth: SCREEN_WIDTH,
  },
  footerLinks: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'space-between',
    paddingBottom: 10,
    fontFamily: Fonts.helveticaMedium,
    fontSize: 14,
  },
  autocompleteTextInput: {
    borderRadius: 25,
    backgroundColor: '#383b42',
    color: '#fff',
    paddingLeft: 18,
  },
  rightButtonsContainerStyle: {
    right: 15,
    height: 30,
    alignSelf: 'center',
  },
  inputContainerStyle: {
    backgroundColor: '#383b42',
    borderRadius: 25,
    marginTop: 20,
  },
  suggestionContainerStyle: {
    backgroundColor: '#383b42',
  },
  autocompleteContainerStyle: {flexGrow: 1, flexShrink: 1},
  autocompleteItemText: {color: '#fff', padding: 15, fontFamily: Fonts.helveticaMedium},
  continueButton: {
    minWidth: 150,
    alignSelf: 'center',
    borderRadius: 40,
    padding: 10,
  },
  continueButtonText: {
    textAlign: 'center',
    fontFamily: Fonts.helveticaMedium,
    fontSize: 18,
  },
  footerText: {
    fontFamily: Fonts.helveticaMedium,
    fontSize: 13,
    color: '#000',
  },
  emptyListPlaceholder: {
    fontFamily: Fonts.helveticaMedium,
    fontSize: 16,
    color: '#FFF',
    padding: 10,
    textAlign: 'center',
  },
});
